language: java
jdk:
    - oraclejdk8

env:
    global:
        - CI_NAME=travis-ci
        - secure: "Xp4AAHnZRPULVx0uphABVcTVNSkT3G9A3q0XYPqcngiw+2t2N0R5QhEFM3PyPzRzUrbns/Wr1asf1HYiTFMU5amckT8edog/W2Nlb5tiOwhXQ5Ji18ctpkhuiFMULKz9Q3EErEfso+V68bpQL4xdZvGUjZ+HGmI8QxPJNaNBH+lfQyU73dzWN1IEzC4hCwP6f65bZ5LsHXmB36IkhiADR0zDZrpaKMMCk0JhjC0JYcemZuSoz2QGQmrZLXpdX+yKdU+KyxKI5cyZ1nuoMorU2EPvMmIlBNGZA9hLA08oBIn/5XG/S7XIULrYg7gzIZLTdz/GjwLPtxNlSMhNi0FyyJUDYCz0prmZdPn88MTGwQZckLSpfJoDyXfK0fFS0VcecgBEaRoSxXQpDi29fpX4ItY7zDJ7lQ7qIW6y5u2SHM966tF4p0Fj/Otldghx+bVQyF3+uveToRvyvXXdGWUlgFqYq0RTS9YTKSAp+pwqJO4x/YrE+J+ykZY5Wqgz0zXzMO43uqiuryGChGJMo01AUcPWIgWA4PgNUJTxpgXdr+orKcifXL2GIX+dOlJehcRFsuHgqViUltAkiyE5sKMM+QQD7d9nUP8vIN0IB1LYe/2iqMKq2mle+7Reco4MZG4ud78k0NUAxktTIr27eSrPyWY18qPaXFCHuib5XgrgcW8="

script:
    - gradle build

after_success:
    - gradle test jacocoTestReport coveralls
